<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Customer Intelligence &amp; Decision Analytics – Nic | Data</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../img/profile.jpeg" rel="icon" type="image/jpeg">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-31f83acc9cd1edb2889821b433ae8ec0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-224726e677151d31706f3872130d660e.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script>
  (function() {
    try {
      var storageKey = 'nic-site-theme';
      var storedTheme = localStorage.getItem(storageKey);
      var prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
      var theme = storedTheme || (prefersDark ? 'dark' : 'light');
      document.documentElement.setAttribute('data-theme', theme);
      document.documentElement.style.colorScheme = theme;
    } catch (error) {
      document.documentElement.setAttribute('data-theme', 'light');
      document.documentElement.style.colorScheme = 'light';
    }
  })();
</script>
<meta name="color-scheme" content="light dark">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,600;1,400&amp;family=DM+Sans:opsz,wght@9..40,300;9..40,400;9..40,500&amp;family=DM+Mono:wght@400&amp;family=Noto+Sans+Condensed:wght@300;400;600;700&amp;display=swap" rel="stylesheet">


</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Nic | Data</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about/index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects/index.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../research/publications.html"> 
<span class="menu-text">Research</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../personal/index.html"> 
<span class="menu-text">Life</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../cv/index.html"> 
<span class="menu-text">CV</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blogs/index.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resources/index.html"> 
<span class="menu-text">Resources</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/gondamol"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/nichodemusamollo/"> <i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="mailto:nichodemuswerre@gmail.com"> 
<span class="menu-text">Get in Touch</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Customer Intelligence &amp; Decision Analytics</h1>
<p class="subtitle lead">From data to decisions — an end-to-end analytics product on a real, open transaction ledger</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div style="padding:4.5rem 0 2.25rem;">
  <span class="section-eyebrow">Analytics product · Real open data · Live dashboard</span>
  <h1 class="section-h" style="font-size:clamp(2.2rem,4vw,3.2rem);margin-top:0.45rem;">Turning a messy transaction ledger into decisions someone can act on.</h1>
  <p class="section-sub" style="margin-bottom:1.6rem;">Two years of real invoices from a UK giftware wholesaler — 1,067,371 lines, published by the UCI Machine Learning Repository — turned into account intelligence, calibrated predictive scores, and an explainable suggested action. Built end to end: acquisition, quality, analytical model, models, decision engine, and a deployed, live application.</p>
  <p style="margin:0;">
    <a href="https://nic-customer-intelligence.streamlit.app/" class="btn-primary" target="_blank" rel="noopener">Open the live dashboard ↗</a>
    <a href="https://github.com/gondamol/customer-intelligence" class="btn-ghost" target="_blank" rel="noopener">Repository &amp; documentation ↗</a>
  </p>
</div>
<div class="cv-stat-grid" style="margin-bottom:2.75rem;">
  <article class="cv-stat-card"><span class="cv-stat-num">1.07m</span><span class="cv-stat-label">Real invoice lines, 24-month panel</span></article>
  <article class="cv-stat-card"><span class="cv-stat-num">22.6%</span><span class="cv-stat-label">Of the ledger belongs to no customer</span></article>
  <article class="cv-stat-card"><span class="cv-stat-num">0.734</span><span class="cv-stat-label">Cross-validated ROC-AUC, lapse model</span></article>
  <article class="cv-stat-card"><span class="cv-stat-num">1.49×</span><span class="cv-stat-label">Recommender lift over popularity</span></article>
</div>
<figure style="margin:0 0 2.75rem;" class="figure">
  <img src="../../img/customer-intelligence/01-executive-view.png" alt="Executive view of the Customer Intelligence dashboard showing headline account figures and revenue by segment" style="width:100%;height:auto;border:1px solid var(--border,#e3e0d9);border-radius:8px;display:block;" class="figure-img">
  <figcaption style="font-size:0.78rem;color:var(--muted,#6b6b6b);margin-top:0.6rem;">The executive view: what is happening, why, where the opportunity is, and what to consider doing. Champions are 18.3% of accounts and 66.9% of revenue. <a href="https://nic-customer-intelligence.streamlit.app/" target="_blank" rel="noopener">Open it live ↗</a></figcaption>
</figure>
<div class="callout-highlight">
<p><strong>Data:</strong> <a href="https://archive.ics.uci.edu/dataset/502/online+retail+ii">Online Retail II</a> — Chen, D. (2012), UCI Machine Learning Repository, used under <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>. Scores and recommendations are my own work and are decision <strong>support</strong>: nothing in the system is an automated decision.</p>
</div>
<section id="why-i-rebuilt-this-on-real-data" class="level2">
<h2 class="anchored" data-anchor-id="why-i-rebuilt-this-on-real-data">Why I rebuilt this on real data</h2>
<p>I first built this on data I generated myself. It looked good — the attrition model scored <strong>0.93</strong> — and that was the problem. A model that good on invented data is measuring how knowable the invention was.</p>
<p>So I sourced open, properly licensed transaction data and rebuilt on it. The architecture did not change. What the numbers mean did.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Synthetic version</th>
<th>On real data</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Attrition model</td>
<td>ROC-AUC 0.93</td>
<td><strong>0.734 ± 0.034</strong></td>
</tr>
<tr class="even">
<td>Data quality defects</td>
<td>16 types, injected by me</td>
<td>Real, and worse</td>
</tr>
<tr class="odd">
<td>Unattributable revenue</td>
<td>none</td>
<td><strong>22.6% of the ledger</strong></td>
</tr>
<tr class="even">
<td>Seasonality</td>
<td>none</td>
<td>3× between February and November</td>
</tr>
</tbody>
</table>
<p>The lower number is the honest one, and every awkward property below is something the invented data simply did not have.</p>
</section>
<section id="the-data-engineering-is-the-substance" class="level2">
<h2 class="anchored" data-anchor-id="the-data-engineering-is-the-substance">The data engineering is the substance</h2>
<p>The source is one flat sheet of invoice lines. Almost everything interesting about it is a problem:</p>
<ul>
<li><strong><code>Invoice</code> and <code>StockCode</code> mix integers with alphanumeric codes.</strong> Read as numbers — which is what a naive load does — every credit note and administrative row silently disappears.</li>
<li><strong>0.57% of stock codes are not products at all</strong>: postage, carriage, manual adjustments, discounts, samples, bank charges, an <strong>Amazon commission of −£260,764</strong>, bad-debt write-offs, gift vouchers, and seventeen rows described as <em>“This is a test product”</em>.</li>
<li><strong><code>M</code> and <code>m</code> are the same manual-adjustment code</strong>, entered two ways. Unified — but for administrative codes only, because product codes are case-significant: <code>84031A</code> and <code>84031B</code> are different items.</li>
<li><strong>22,950 negative quantities.</strong> Returns are <em>separated</em>, not netted off. Netting makes an account that buys £10,000 and returns £9,000 identical to one that buys £1,000 and returns nothing.</li>
<li><strong>243,007 lines carry no customer identifier.</strong> Real revenue that belongs to nobody. It stays in the revenue totals and is excluded from every account-level figure — and the site says so, because that is the difference between a measurement and a claim.</li>
<li><strong>5,305 stock codes and no categories.</strong> A derived keyword taxonomy carries 87.7% of revenue into eleven named categories. A published judgement, not a fact about the data.</li>
</ul>
</section>
<section id="the-decision-that-mattered-most-was-a-window-not-a-model" class="level2">
<h2 class="anchored" data-anchor-id="the-decision-that-mattered-most-was-a-window-not-a-model">The decision that mattered most was a window, not a model</h2>
<p>This business takes <strong>84,711 invoice lines in November 2011 and 27,707 in February</strong>. That single fact determined the experimental design:</p>
<pre style="font-size:0.8rem;line-height:1.6;overflow-x:auto;background:var(--surface,#fbfaf8);border:1px solid var(--border,#e3e0d9);border-radius:6px;padding:1.1rem 1.2rem;">train   features months  1–12  (Dec 09 – Nov 10) → outcome 13–15  (Dec 10 – Feb 11)
score   features months 13–24  (Dec 10 – Nov 11) → outcome 25–27  (Dec 11 – Feb 12, unobserved)
</pre>
<p>Both feature windows are twelve whole months, so seasonality averages out inside them. <strong>Both outcome windows are December–February</strong>, so the model is applied to the season it was trained on. A test enforces it.</p>
<p>The same reasoning fixed the growth model. The obvious target — “beats its own annual quarterly run-rate” — is wrong in a seasonal business: in a low quarter most accounts fall below their annual average whatever they do, and the model spends its capacity learning the calendar. Comparing <strong>the same quarter a year earlier</strong> moved ROC-AUC from <strong>0.62 to 0.68</strong> on identical features.</p>
</section>
<section id="what-the-models-do" class="level2">
<h2 class="anchored" data-anchor-id="what-the-models-do">What the models do</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th>Question</th>
<th>Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Lapse risk</strong></td>
<td>Will an established account place no order next quarter?</td>
<td>Cross-validated ROC-AUC <strong>0.734 ± 0.034</strong>, lift 1.66×</td>
</tr>
<tr class="even">
<td><strong>Growth propensity</strong></td>
<td>Will it beat the same quarter a year earlier?</td>
<td>Cross-validated ROC-AUC <strong>0.684 ± 0.030</strong>, lift 2.00×</td>
</tr>
<tr class="odd">
<td><strong>Next best product</strong></td>
<td>What should we lead with?</td>
<td>hit@5 <strong>0.314</strong> vs 0.211 popularity — <strong>1.49× lift</strong></td>
</tr>
</tbody>
</table>
<p>Both classifiers are quoted <strong>cross-validated with a spread</strong>, not on a single held-out split. Re-running the project with the rows in a different order moved a held-out AUC by 0.05 — about two standard errors on this sample, and enough to report as an improvement something that is only a different shuffle. The single split flattered both models by 0.03–0.04, in the same direction.</p>
<p>Both are calibrated in the large to three decimal places: predicted 0.451 against observed 0.454, and 0.239 against 0.240.</p>
<section id="a-defect-that-roc-auc-could-not-see" class="level3">
<h3 class="anchored" data-anchor-id="a-defect-that-roc-auc-could-not-see">A defect that ROC-AUC could not see</h3>
<p>An account that had ordered the <em>previous month</em>, and was active in eight months of twelve, was scored at a <strong>97.6% probability of lapsing</strong>. Its largest month sat fourteen standard deviations above the book mean and its returned value twenty — so the linear model was extrapolating far outside anything it had been trained on, and the sigmoid had saturated. I found it on the live dashboard, on the flagship page.</p>
<p><strong>The AUC did not move when I fixed it.</strong> It is a ranking metric, the ranking was fine, and only the scores were nonsense — the same blind spot that had earlier hidden a calibration failure in this project.</p>
<p>The fix is standard: log-transform the heavy-tailed money and count features before standardising. Monotone, so nothing about the ordering changes; defined at zero, which matters because most of these are zero for somebody; and it turns “fourteen standard deviations” into “a large account”. Afterwards that account scores <strong>0.112</strong>, no account exceeds 0.90, and discrimination is unchanged at 0.734. A test now fails the build if it returns.</p>
</section>
<section id="two-negative-results-published" class="level3">
<h3 class="anchored" data-anchor-id="two-negative-results-published">Two negative results, published</h3>
<p>A <strong>category-expansion classifier</strong> scored ROC-AUC <strong>0.550</strong> — barely above chance. A <strong>category-level recommender</strong> then failed to beat a popularity baseline (0.927 against 0.936).</p>
<p>Both failed for the same structural reason, and finding it mattered more than either model would have: <strong>the median account already buys 9 of the 12 categories</strong>. “The top three you don’t buy” is most of what is left, so there is almost nothing to predict.</p>
<p>Reframed to <strong>product</strong> level — 400 products, median account buys 18 — the problem is real, and item-to-item collaborative filtering beats popularity by 1.49× at k=5. It can also name the product an account manager should lead with, which a propensity score never could.</p>
<p>The answer was to change the question, not to reach for a bigger model.</p>
<figure style="margin:1.75rem 0 2rem;" class="figure">
  <img src="../../img/customer-intelligence/05-decision-support.png" alt="Decision support page showing one account's evidence, the rule that fired, what to lead with, and the constraints on acting" style="width:100%;height:auto;border:1px solid var(--border,#e3e0d9);border-radius:8px;display:block;" class="figure-img">
  <figcaption style="font-size:0.78rem;color:var(--muted,#6b6b6b);margin-top:0.6rem;">One account: the evidence, which rule fired, the product to lead with, the constraint on acting, and how much confidence the trading history supports.</figcaption>
</figure>
</section>
</section>
<section id="from-prediction-to-action" class="level2">
<h2 class="anchored" data-anchor-id="from-prediction-to-action">From prediction to action</h2>
<p>A probability is not a decision. The decision engine is a transparent ordered rule set rather than a model — a recommendation has to be arguable by the account manager who receives it, the rules encode commercial policy that should change deliberately, and learning actions from last year learns last year’s policy including its mistakes.</p>
<p>The ordering <em>is</em> the policy:</p>
<ol type="1">
<li><strong>Service failure</strong> — a 20%+ return rate is not a sales opportunity.</li>
<li><strong>Too new to judge</strong> — onboarding, not a low-value label.</li>
<li><strong>Not scored</strong> — says so, rather than implying a judgement never made.</li>
<li><strong>Retention</strong> — graded by what the account is worth and how far past its own usual gap it has drifted.</li>
<li><strong>Growth</strong> — only on an account that is not going anywhere.</li>
<li><strong>Deliberately nothing</strong> — a reachable outcome, recorded as a decision.</li>
</ol>
<p><strong>17% of accounts reach a named account manager, and they hold 53% of revenue.</strong> An engine routing much more than that to human contact has produced a wish list rather than a plan, so the check sits on the page.</p>
<section id="the-accounts-the-models-refuse-to-score" class="level3">
<h3 class="anchored" data-anchor-id="the-accounts-the-models-refuse-to-score">The accounts the models refuse to score</h3>
<p>Only <strong>1,703 of 5,914</strong> accounts have an established ordering rhythm. The rest carry no score, sit in a <strong>“Not scored”</strong> quadrant, and their recommendation says why.</p>
<p>That was a bug I had to fix. Filling their risk with 1.0 to make the arithmetic work put them in the <em>Retain</em> quadrant — flagged as high-risk on the strength of a number the model had explicitly declined to produce. Enforcing eligibility at scoring time as well as training time cut the account-manager workload from 45% of the book to 17%.</p>
</section>
</section>
<section id="the-data-quality-section-is-real-now" class="level2">
<h2 class="anchored" data-anchor-id="the-data-quality-section-is-real-now">The data quality section is real now</h2>
<div class="cv-stat-grid" style="grid-template-columns:repeat(2,minmax(0,1fr));margin:2rem 0 1.25rem;">
  <article class="cv-stat-card"><span class="cv-stat-num">97.3%</span><span class="cv-stat-label">of records conform to the quality rules</span></article>
  <article class="cv-stat-card"><span class="cv-stat-num">22.6%</span><span class="cv-stat-label">of the ledger belongs to no customer at all</span></article>
</div>
<p>Both figures describe the same data. Conformance is a row-weighted average and at these defect rates it is arithmetically bound to look reassuring — it is the wrong number to lead with. The one that changes what the analysis can <em>claim</em> is the second.</p>
<p>Twenty-two rules across seven dimensions found 235,143 unattributable lines, 34,058 exact duplicates, 3,427 negative quantities on invoices that are not credit notes, 1,215 stock codes carrying conflicting descriptions, and seventeen test rows in production data. None of it was injected.</p>
<section id="how-do-i-know-the-checks-work" class="level3">
<h3 class="anchored" data-anchor-id="how-do-i-know-the-checks-work">How do I know the checks work?</h3>
<p>On real data the answer is not known in advance, so the checks cannot be graded against it. So they are graded elsewhere: the synthetic generator from the first version of this project is retained as a <strong>validation harness</strong>. It injects sixteen defect types in known quantities, and the reconciliation of injected against detected is a test the build must pass. The complementary test matters as much — the same rules run over the <em>undamaged</em> data must all pass, or a check that always fires would look like a working detector.</p>
<p>Prove the instrument reads correctly against a known answer, then point it at data where the answer is unknown.</p>
<figure style="margin:1.75rem 0 2rem;" class="figure">
  <img src="../../img/customer-intelligence/06-data-quality.png" alt="Data quality and governance page showing provenance, licensing, and the real defects found in the source data" style="width:100%;height:auto;border:1px solid var(--border,#e3e0d9);border-radius:8px;display:block;" class="figure-img">
  <figcaption style="font-size:0.78rem;color:var(--muted,#6b6b6b);margin-top:0.6rem;">Provenance, licence, and what is actually wrong with a widely used published dataset.</figcaption>
</figure>
</section>
</section>
<section id="governance-as-code" class="level2">
<h2 class="anchored" data-anchor-id="governance-as-code">Governance as code</h2>
<ul>
<li><strong>Attribution.</strong> CC BY 4.0 makes credit a condition of use, not a courtesy. The source, publisher, licence and citation are carried in code and shown on every page.</li>
<li><strong>Provenance.</strong> Each file is downloaded from its original publisher at build time and cached by SHA-256. A source that changes upstream is reported rather than silently changing every figure downstream.</li>
<li><strong>Leakage.</strong> Training and scoring features come from the <em>same SQL file</em> with a different window. A test greps the SQL for any month literal reaching into the outcome window.</li>
<li><strong>Eligibility.</strong> Models refuse to score outside the population they were fitted on. Ineligible accounts get null, not zero — zero is a prediction, null is an admission.</li>
<li><strong>Nothing dropped silently.</strong> Every removed line is counted with the rule and the reasoning, including the 235,143 that belong to nobody.</li>
</ul>
</section>
<section id="how-this-connects-to-what-i-already-do" class="level2">
<h2 class="anchored" data-anchor-id="how-this-connects-to-what-i-already-do">How this connects to what I already do</h2>
<p>The techniques are the same discipline pointed at a different subject.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>In this project</th>
<th>In work I have delivered</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Quality rules graded against a known answer</td>
<td>High-frequency checks and automated quality workflows on the health financial diaries study</td>
</tr>
<tr class="even">
<td>Conformance log — nothing dropped silently</td>
<td>Data quality architecture for multi-year oncology records</td>
</tr>
<tr class="odd">
<td>Decision engine with stated guardrails</td>
<td>Shiny decision-support for IRC field teams, from causal forest targeting models</td>
</tr>
<tr class="even">
<td>Account 360 from a flat ledger</td>
<td>Research data management across multi-country programme systems</td>
</tr>
<tr class="odd">
<td>An application that reads artefacts</td>
<td>Real-time field dashboards and operational apps</td>
</tr>
<tr class="even">
<td>Cross-validated estimates with spreads</td>
<td>Mixed-methods research and survival analysis</td>
</tr>
</tbody>
</table>
<pre><code>Data management → Analytics → Statistical modelling → Decision support → Analytics products</code></pre>
</section>
<section id="limitations" class="level2">
<h2 class="anchored" data-anchor-id="limitations">Limitations</h2>
<p>One business, two years, one country of origin — a UK giftware wholesaler selling largely to trade customers, so nothing generalises without re-fitting. The lapse label is <em>behavioural</em>, not contractual: a wholesale customer cannot cancel, only stop ordering. 22.6% of the ledger is unattributable, so every per-account figure describes the 77% that can be attributed. The product taxonomy is derived by keyword rules — a published judgement covering 87.7% of revenue. 1,752 accounts train the lapse model, which is small and is why the reported spreads are what they are. Two years is two Christmases: enough to align the windows seasonally, not enough to model seasonality itself. And no causal claim is supported anywhere — permutation importance measures what a model relies on, not what causes an account to lapse.</p>
</section>
<section id="running-it" class="level2">
<h2 class="anchored" data-anchor-id="running-it">Running it</h2>
<div class="sourceCode" id="cb2"><pre class="sourceCode bash"><code class="sourceCode bash"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> clone https://github.com/gondamol/customer-intelligence.git</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="bu">cd</span> customer-intelligence</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">make</span> setup      <span class="co"># create the environment</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">make</span> run        <span class="co"># open the application — derived artefacts are committed</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">make</span> all        <span class="co"># or rebuild everything from the published source</span></span></code></pre></div>
<p>The application starts immediately: the artefacts it reads are in the repository, so there is no build step and no data download at start-up. <code>make all</code> re-fetches Online Retail II from UCI and rebuilds the whole pipeline. 123 tests cover the source adapter, the conformed layer, seasonal window alignment, leakage controls, model behaviour, the decision rules and the recommender.</p>
<div style="margin:2.5rem 0 1rem;">
  <a href="https://nic-customer-intelligence.streamlit.app/" class="btn-primary" target="_blank" rel="noopener">Open the live dashboard ↗</a>
  <a href="https://github.com/gondamol/customer-intelligence" class="btn-ghost" target="_blank" rel="noopener">Repository ↗</a>
  <a href="../index.html" class="btn-ghost">All projects</a>
</div>
<div class="callout-highlight">
<p><strong>The domain may change. The analytical problem remains: turning complex data into better decisions.</strong></p>
</div>


</section>

</main> <!-- /main -->
<script>
(function() {
  var storageKey = 'nic-site-theme';
  var moonIcon = '' +
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">' +
    '<path d="M21 12.8A9 9 0 1 1 11.2 3a7 7 0 0 0 9.8 9.8z"></path>' +
    '</svg>';
  var sunIcon = '' +
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">' +
    '<circle cx="12" cy="12" r="4.2"></circle>' +
    '<path d="M12 2.5v2.2M12 19.3v2.2M4.9 4.9l1.6 1.6M17.5 17.5l1.6 1.6M2.5 12h2.2M19.3 12h2.2M4.9 19.1l1.6-1.6M17.5 6.5l1.6-1.6"></path>' +
    '</svg>';

  function readStoredTheme() {
    try {
      return localStorage.getItem(storageKey);
    } catch (error) {
      return null;
    }
  }

  function persistTheme(theme) {
    try {
      localStorage.setItem(storageKey, theme);
    } catch (error) {
      // Ignore storage failures; the in-memory theme still works.
    }
  }

  function applyTheme(theme, persist) {
    var root = document.documentElement;
    var toggle = document.querySelector('.theme-toggle');
    var navbar = document.querySelector('.navbar');

    root.setAttribute('data-theme', theme);
    root.style.colorScheme = theme;

    if (navbar) {
      navbar.setAttribute('data-bs-theme', theme === 'dark' ? 'dark' : 'light');
    }

    if (toggle) {
      var nextTheme = theme === 'dark' ? 'light' : 'dark';
      var label = toggle.querySelector('.theme-toggle__label');
      var icon = toggle.querySelector('.theme-toggle__icon');
      toggle.setAttribute('aria-pressed', theme === 'dark' ? 'true' : 'false');
      toggle.setAttribute('aria-label', theme === 'dark' ? 'Switch to light mode' : 'Switch to dark mode');
      toggle.dataset.theme = theme;
      if (label) label.textContent = theme === 'dark' ? 'Light' : 'Dark';
      if (icon) icon.innerHTML = theme === 'dark' ? sunIcon : moonIcon;
      toggle.dataset.nextTheme = nextTheme;
    }

    if (persist !== false) {
      persistTheme(theme);
    }
  }

  function detectTheme() {
    var storedTheme = readStoredTheme();
    if (storedTheme === 'light' || storedTheme === 'dark') {
      return storedTheme;
    }
    return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
  }

  function injectToggle() {
    var host = document.querySelector('.quarto-navbar-tools');
    if (!host || host.querySelector('.theme-toggle')) return;

    var button = document.createElement('button');
    button.type = 'button';
    button.className = 'theme-toggle';
    button.innerHTML = '<span class="theme-toggle__icon"></span><span class="theme-toggle__label"></span>';
    button.addEventListener('click', function() {
      var currentTheme = document.documentElement.getAttribute('data-theme') || 'light';
      applyTheme(currentTheme === 'dark' ? 'light' : 'dark');
    });

    host.prepend(button);
    applyTheme(detectTheme(), false);
  }

  document.addEventListener('DOMContentLoaded', function() {
    injectToggle();

    var mediaQuery = window.matchMedia('(prefers-color-scheme: dark)');
    var onThemeChange = function(event) {
      if (readStoredTheme()) return;
      applyTheme(event.matches ? 'dark' : 'light', false);
    };

    if (typeof mediaQuery.addEventListener === 'function') {
      mediaQuery.addEventListener('change', onThemeChange);
    } else if (typeof mediaQuery.addListener === 'function') {
      mediaQuery.addListener(onThemeChange);
    }
  });
})();
</script>
<script>
(function() {
  function initGalleryLightbox() {
    var galleryImages = Array.prototype.slice.call(document.querySelectorAll('.gallery-grid .gal-img'));
    if (!galleryImages.length || document.querySelector('.site-lightbox')) return;

    var overlay = document.createElement('div');
    overlay.className = 'site-lightbox';
    overlay.setAttribute('hidden', 'hidden');
    overlay.innerHTML =
      '<button type="button" class="site-lightbox__close" aria-label="Close image viewer">Close</button>' +
      '<div class="site-lightbox__dialog" role="dialog" aria-modal="true" aria-label="Expanded image view">' +
        '<img class="site-lightbox__image" alt="">' +
        '<p class="site-lightbox__caption"></p>' +
      '</div>';
    document.body.appendChild(overlay);

    var closeBtn = overlay.querySelector('.site-lightbox__close');
    var lightboxImage = overlay.querySelector('.site-lightbox__image');
    var lightboxCaption = overlay.querySelector('.site-lightbox__caption');
    var lastTrigger = null;

    function closeLightbox() {
      overlay.setAttribute('hidden', 'hidden');
      document.body.classList.remove('lightbox-open');
      if (lastTrigger) lastTrigger.focus();
    }

    function openLightbox(img) {
      lastTrigger = img;
      lightboxImage.src = img.currentSrc || img.src;
      lightboxImage.alt = img.alt || '';

      var overlayLabel = '';
      var labelNode = img.closest('.gal-ph');
      if (labelNode) {
        var textNode = labelNode.querySelector('.gal-label');
        if (textNode) overlayLabel = textNode.textContent || '';
      }
      lightboxCaption.textContent = overlayLabel || img.alt || '';

      overlay.removeAttribute('hidden');
      document.body.classList.add('lightbox-open');
      closeBtn.focus();
    }

    galleryImages.forEach(function(img) {
      img.setAttribute('tabindex', '0');
      img.setAttribute('role', 'button');
      img.setAttribute('aria-label', (img.alt || 'Open image') + ' (expanded view)');
      img.addEventListener('click', function() { openLightbox(img); });
      img.addEventListener('keydown', function(event) {
        if (event.key === 'Enter' || event.key === ' ') {
          event.preventDefault();
          openLightbox(img);
        }
      });
    });

    closeBtn.addEventListener('click', closeLightbox);
    overlay.addEventListener('click', function(event) {
      if (event.target === overlay) closeLightbox();
    });
    document.addEventListener('keydown', function(event) {
      if (event.key === 'Escape' && !overlay.hasAttribute('hidden')) {
        closeLightbox();
      }
    });
  }

  function initContactForm() {
    var form = document.getElementById('contactForm');
    if (!form) return;

    var submitBtn = document.getElementById('sendBtn');
    var statusEl = document.getElementById('contactFormStatus');
    var endpoint = form.getAttribute('action');

    function setStatus(message, state) {
      if (!statusEl) return;
      statusEl.textContent = message;
      statusEl.dataset.state = state || '';
    }

    form.addEventListener('submit', function(event) {
      event.preventDefault();

      if (!endpoint) {
        setStatus('Form endpoint is missing. Please try the email link instead.', 'error');
        return;
      }

      var formData = new FormData(form);
      if (formData.get('_gotcha')) {
        return;
      }

      if (submitBtn) {
        submitBtn.disabled = true;
        submitBtn.textContent = 'Sending...';
      }
      setStatus('Sending your message...', 'pending');

      fetch(endpoint, {
        method: 'POST',
        headers: {
          Accept: 'application/json'
        },
        body: formData
      })
        .then(function(response) {
          if (!response.ok) {
            throw new Error('Request failed');
          }
          return response.json();
        })
        .then(function() {
          form.reset();
          setStatus('Message sent. You should receive it in your inbox shortly.', 'success');
          if (submitBtn) {
            submitBtn.textContent = 'Message Sent ✓';
          }
        })
        .catch(function() {
          setStatus('The form could not be sent right now. Please use the email link if this keeps happening.', 'error');
          if (submitBtn) {
            submitBtn.disabled = false;
            submitBtn.textContent = 'Send Message →';
          }
        });
    });
  }

  document.addEventListener('DOMContentLoaded', function() {
    initGalleryLightbox();
    initContactForm();
  });
})();
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/gondamol\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p><span class="footer-title">Nichodemus Amollo</span><span class="footer-meta">Research Data Systems · Health &amp; Development Programmes</span></p>
</div>   
    <div class="nav-footer-center">
<p><a href="tel:+254725737867" class="footer-phone">+254 725 737 867</a><span class="footer-meta">Nairobi, Kenya · Open to remote and hybrid work</span></p>
</div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/gondamol">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/nichodemusamollo/">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="../../cv/index.html">
<p>CV</p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>